import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          padding: "150px 0",
          fontSize: "30px",
          fontWeight: "700",
          border: "1px solid #000",
          textAlign: "center",
        }}>
        판다마켓
      </div>
    </>
  );
}
